source 'https://rubygems.org'
gem 'rack'
gem 'rake'
gem 'm2h'
gem 'http'
gem 'zip'
gem 'ruby-saml','1.6.0'
gem 'chartkick','3.1.0'
gem 'ruby-openid','2.8.0'
gem 'mini_magick','4.9.3'
gem 'puppet','2.8'

